//
// auto-generated by ops.py//

//header
#define OPS_API 2
#define OPS_3D
#include "ops_lib_cpp.h"

#include "ops_cuda_rt_support.h"
#include "ops_cuda_reduction.h"

#include <cuComplex.h>

#define OPS_FUN_PREFIX __device__ __host__
#include "user_types.h"
#ifdef OPS_MPI
#include "ops_mpi_core.h"
#endif
// global constants

void ops_init_backend() {}

void ops_decl_const_char(int dim, char const *type,
int size, char *dat, char const *name){
  {
    printf("error: unknown const name\n"); exit(1);
  }
}


//user kernel files
#include "kernel_copy_cuda_kernel.cu"
#include "kernel_populate_cuda_kernel.cu"
#include "kernel_initialguess_cuda_kernel.cu"
#include "jac3D_kernel_stencil_cuda_kernel.cu"
